repos:
  # Frontend checks
  - repo: local
    hooks:
      - id: format check
        name: running format check
        language: system
        entry: npm run format
        pass_filenames: false
        require_serial: true
      - id: lint check
        name: running lint check
        language: system
        entry: npm run lint
        pass_filenames: false
        require_serial: true
      - id: test check
        name: running test check
        language: system
        entry: npm run test:run
        pass_filenames: false
        require_serial: true

  # General checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        skip: true
      - id: check-merge-conflict
        skip: true
