services:
  db:
    # Note: we need to use the pgvector/pgvector:pg17 image to use the pgvector extension, instead of the official postgres image
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local_db
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build: ./backend
    # this overrides the default CMD specified in the Dockerfile, use this for local development
    command: fastapi dev app/main.py --host 0.0.0.0 --port 8000
    # This will make the .env file available to the container       
    env_file:
      - .env
    # need to override DATABASE_URL in .env to point to the db service in docker-compose, @db instead of @localhost
    # environment:
    # TODO: break down to env variable in db
      # - DATABASE_URL=postgresql://user:password@db:5432/local_db      
    # useful for development, changes take effect in the container without needing to rebuild the image.
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
