services:
  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    restart: unless-stopped