services:
  db:
    # Note: we need to use the pgvector/pgvector:pg17 image to use the pgvector extension, instead of the official postgres image
    image: pgvector/pgvector:pg17
    env_file:
      - .env    
    environment:
      POSTGRES_USER: ${SERVER_DB_USER?Variable not set}
      POSTGRES_PASSWORD: ${SERVER_DB_PASSWORD?Variable not set}
      POSTGRES_DB: ${SERVER_DB_NAME?Variable not set}
    ports:
      - "${SERVER_DB_PORT?Variable not set}:${SERVER_DB_PORT?Variable not set}"
    restart: no

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    # this overrides the default CMD specified in the Dockerfile, use this for local development
    command: fastapi dev server/main.py --host 0.0.0.0 --port 8000
    env_file:
      - .env
    environment:
      # override the default SERVER_DB_HOST value in .env
      SERVER_DB_HOST: db
    # useful for development, changes take effect in the container without needing to rebuild the image.
    volumes:
      - ./aipolabs/server:/aipolabs/server
      - ./aipolabs/common:/aipolabs/common
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: no

